spring.application.name=nexus

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_nexus
spring.datasource.username=${DBUSERNAME:root}
spring.datasource.password=${DBUSERPASSWORD:}